"""The single source of truth for modules and the Blind 75.

Edit this file, then run ./sync. PROBLEMS.md, the leetcode/ index, and the
progress numbers in README.md are all generated from it.
"""

# (number, name, leetcode/ folder name)
MODULES = [
    ("00", "Foundations",       None),
    ("01", "Arrays & Hashing",  "01_arrays_hashing"),
    ("02", "Two Pointers",      "02_two_pointers"),
    ("03", "Sliding Window",    "03_sliding_window"),
    ("04", "Stack",             "04_stack"),
    ("05", "Binary Search",     "05_binary_search"),
    ("06", "Linked List",       "06_linked_list"),
    ("07", "Trees",             "07_trees"),
    ("08", "Tries",             "08_tries"),
    ("09", "Heap / Priority Queue", "09_heap"),
    ("10", "Backtracking",      "10_backtracking"),
    ("11", "Graphs",            "11_graphs"),
    ("12", "Advanced Graphs",   "12_advanced_graphs"),
    ("13", "1-D Dynamic Programming", "13_1d_dp"),
    ("14", "2-D Dynamic Programming", "14_2d_dp"),
    ("15", "Greedy",            "15_greedy"),
    ("16", "Intervals",         "16_intervals"),
    ("17", "Bit Manipulation",  "17_bit_manipulation"),
    ("18", "Math & Geometry",   "18_math_geometry"),
]

# (module, LeetCode id, title, slug, difficulty, premium)
# Checked against LeetCode's API by tools/verify_catalog.py.
BLIND_75 = [
    ("01", 217,  "Contains Duplicate",                    "contains-duplicate",                     "Easy",   False),
    ("01", 242,  "Valid Anagram",                         "valid-anagram",                          "Easy",   False),
    ("01", 1,    "Two Sum",                               "two-sum",                                "Easy",   False),
    ("01", 49,   "Group Anagrams",                        "group-anagrams",                         "Medium", False),
    ("01", 347,  "Top K Frequent Elements",               "top-k-frequent-elements",                "Medium", False),
    ("01", 238,  "Product of Array Except Self",          "product-of-array-except-self",           "Medium", False),
    ("01", 271,  "Encode and Decode Strings",             "encode-and-decode-strings",              "Medium", True),
    ("01", 128,  "Longest Consecutive Sequence",          "longest-consecutive-sequence",           "Medium", False),
    ("02", 125,  "Valid Palindrome",                      "valid-palindrome",                       "Easy",   False),
    ("02", 15,   "3Sum",                                  "3sum",                                   "Medium", False),
    ("02", 11,   "Container With Most Water",             "container-with-most-water",              "Medium", False),
    ("03", 121,  "Best Time to Buy and Sell Stock",       "best-time-to-buy-and-sell-stock",        "Easy",   False),
    ("03", 3,    "Longest Substring Without Repeating Characters", "longest-substring-without-repeating-characters", "Medium", False),
    ("03", 424,  "Longest Repeating Character Replacement", "longest-repeating-character-replacement", "Medium", False),
    ("03", 76,   "Minimum Window Substring",              "minimum-window-substring",               "Hard",   False),
    ("04", 20,   "Valid Parentheses",                     "valid-parentheses",                      "Easy",   False),
    ("05", 153,  "Find Minimum in Rotated Sorted Array",  "find-minimum-in-rotated-sorted-array",   "Medium", False),
    ("05", 33,   "Search in Rotated Sorted Array",        "search-in-rotated-sorted-array",         "Medium", False),
    ("06", 206,  "Reverse Linked List",                   "reverse-linked-list",                    "Easy",   False),
    ("06", 21,   "Merge Two Sorted Lists",                "merge-two-sorted-lists",                 "Easy",   False),
    ("06", 143,  "Reorder List",                          "reorder-list",                           "Medium", False),
    ("06", 19,   "Remove Nth Node From End of List",      "remove-nth-node-from-end-of-list",       "Medium", False),
    ("06", 141,  "Linked List Cycle",                     "linked-list-cycle",                      "Easy",   False),
    ("06", 23,   "Merge k Sorted Lists",                  "merge-k-sorted-lists",                   "Hard",   False),
    ("07", 226,  "Invert Binary Tree",                    "invert-binary-tree",                     "Easy",   False),
    ("07", 104,  "Maximum Depth of Binary Tree",          "maximum-depth-of-binary-tree",           "Easy",   False),
    ("07", 100,  "Same Tree",                             "same-tree",                              "Easy",   False),
    ("07", 572,  "Subtree of Another Tree",               "subtree-of-another-tree",                "Easy",   False),
    ("07", 235,  "Lowest Common Ancestor of a Binary Search Tree", "lowest-common-ancestor-of-a-binary-search-tree", "Medium", False),
    ("07", 102,  "Binary Tree Level Order Traversal",     "binary-tree-level-order-traversal",      "Medium", False),
    ("07", 98,   "Validate Binary Search Tree",           "validate-binary-search-tree",            "Medium", False),
    ("07", 230,  "Kth Smallest Element in a BST",         "kth-smallest-element-in-a-bst",          "Medium", False),
    ("07", 105,  "Construct Binary Tree from Preorder and Inorder Traversal", "construct-binary-tree-from-preorder-and-inorder-traversal", "Medium", False),
    ("07", 124,  "Binary Tree Maximum Path Sum",          "binary-tree-maximum-path-sum",           "Hard",   False),
    ("07", 297,  "Serialize and Deserialize Binary Tree", "serialize-and-deserialize-binary-tree",  "Hard",   False),
    ("08", 208,  "Implement Trie (Prefix Tree)",          "implement-trie-prefix-tree",             "Medium", False),
    ("08", 211,  "Design Add and Search Words Data Structure", "design-add-and-search-words-data-structure", "Medium", False),
    ("08", 212,  "Word Search II",                        "word-search-ii",                         "Hard",   False),
    ("09", 295,  "Find Median from Data Stream",          "find-median-from-data-stream",           "Hard",   False),
    ("10", 39,   "Combination Sum",                       "combination-sum",                        "Medium", False),
    ("10", 79,   "Word Search",                           "word-search",                            "Medium", False),
    ("11", 200,  "Number of Islands",                     "number-of-islands",                      "Medium", False),
    ("11", 133,  "Clone Graph",                           "clone-graph",                            "Medium", False),
    ("11", 417,  "Pacific Atlantic Water Flow",           "pacific-atlantic-water-flow",            "Medium", False),
    ("11", 207,  "Course Schedule",                       "course-schedule",                        "Medium", False),
    ("11", 261,  "Graph Valid Tree",                      "graph-valid-tree",                       "Medium", True),
    ("11", 323,  "Number of Connected Components in an Undirected Graph", "number-of-connected-components-in-an-undirected-graph", "Medium", True),
    ("12", 269,  "Alien Dictionary",                      "alien-dictionary",                       "Hard",   True),
    ("13", 70,   "Climbing Stairs",                       "climbing-stairs",                        "Easy",   False),
    ("13", 198,  "House Robber",                          "house-robber",                           "Medium", False),
    ("13", 213,  "House Robber II",                       "house-robber-ii",                        "Medium", False),
    ("13", 5,    "Longest Palindromic Substring",         "longest-palindromic-substring",          "Medium", False),
    ("13", 647,  "Palindromic Substrings",                "palindromic-substrings",                 "Medium", False),
    ("13", 91,   "Decode Ways",                           "decode-ways",                            "Medium", False),
    ("13", 322,  "Coin Change",                           "coin-change",                            "Medium", False),
    ("13", 152,  "Maximum Product Subarray",              "maximum-product-subarray",               "Medium", False),
    ("13", 139,  "Word Break",                            "word-break",                             "Medium", False),
    ("13", 300,  "Longest Increasing Subsequence",        "longest-increasing-subsequence",         "Medium", False),
    ("14", 62,   "Unique Paths",                          "unique-paths",                           "Medium", False),
    ("14", 1143, "Longest Common Subsequence",            "longest-common-subsequence",             "Medium", False),
    ("15", 53,   "Maximum Subarray",                      "maximum-subarray",                       "Medium", False),
    ("15", 55,   "Jump Game",                             "jump-game",                              "Medium", False),
    ("16", 57,   "Insert Interval",                       "insert-interval",                        "Medium", False),
    ("16", 56,   "Merge Intervals",                       "merge-intervals",                        "Medium", False),
    ("16", 435,  "Non-overlapping Intervals",             "non-overlapping-intervals",              "Medium", False),
    ("16", 252,  "Meeting Rooms",                         "meeting-rooms",                          "Easy",   True),
    ("16", 253,  "Meeting Rooms II",                      "meeting-rooms-ii",                       "Medium", True),
    ("17", 191,  "Number of 1 Bits",                      "number-of-1-bits",                       "Easy",   False),
    ("17", 338,  "Counting Bits",                         "counting-bits",                          "Easy",   False),
    ("17", 190,  "Reverse Bits",                          "reverse-bits",                           "Easy",   False),
    ("17", 268,  "Missing Number",                        "missing-number",                         "Easy",   False),
    ("17", 371,  "Sum of Two Integers",                   "sum-of-two-integers",                    "Medium", False),
    ("18", 48,   "Rotate Image",                          "rotate-image",                           "Medium", False),
    ("18", 54,   "Spiral Matrix",                         "spiral-matrix",                          "Medium", False),
    ("18", 73,   "Set Matrix Zeroes",                     "set-matrix-zeroes",                      "Medium", False),
]

# Solved on LeetCode but not written up in leetcode/ yet (by LeetCode id).
# Anything with a file in leetcode/ counts as solved automatically.
SOLVED_WITHOUT_WRITEUP = {1, 125}
