"""Regenerate every index and progress number from the source files.

    ./sync           rewrite PROBLEMS.md, leetcode/README.md, README.md progress,
                     and the module table in ROADMAP.md
    ./sync --check   change nothing; exit 1 if any of them are out of date (CI)

Sources:
    tools/catalog.py           modules, the Blind 75, problems solved without a write-up
    leetcode/<module>/NNNN_*.py  written-up solutions (read from each file's header)
    problems/mNN_*/*.py          practice stubs (found by their "LC NNN." docstrings)
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from catalog import BLIND_75, MODULE_SUMMARY, MODULES, SOLVED_WITHOUT_WRITEUP  # noqa: E402

DOT = {"Easy": "🟢", "Medium": "🟡", "Hard": "🔴"}
LEVELS = ("Easy", "Medium", "Hard")
MODULE_NAME = {num: name for num, name, _ in MODULES}
FOLDER_MODULE = {folder: num for num, _, folder in MODULES if folder}
GENERATED = "<!-- Generated by ./sync. Edit tools/catalog.py or the solution files instead. -->"


def lc_url(slug):
    return f"https://leetcode.com/problems/{slug}/"


def bar(done, total, width=20):
    filled = round(width * done / total) if total else 0
    return "█" * filled + "░" * (width - filled)


# ---------------------------------------------------------------- read sources

def read_writeups():
    """leetcode/<folder>/NNNN_slug.py -> {id: info}, parsed from the file header."""
    found = {}
    for path in sorted((ROOT / "leetcode").glob("*/[0-9]*.py")):
        folder = path.parent.name
        if folder not in FOLDER_MODULE:
            sys.exit(f"{path}: folder '{folder}' isn't a module in tools/catalog.py")
        text = path.read_text(encoding="utf-8")
        doc = text.split('"""')[1] if text.count('"""') >= 2 else ""
        first = doc.strip().split("\n")[0]
        m = re.match(r"(\d+)\.\s+(.+?)\s+·\s+(Easy|Medium|Hard)\b", first)
        if not m:
            sys.exit(f"{path}: first docstring line must look like "
                     f"'121. Title  ·  Easy  ·  ...' (got {first!r})")
        lc_id, title, difficulty = int(m.group(1)), m.group(2), m.group(3)
        if not path.name.startswith(f"{lc_id:04d}_"):
            sys.exit(f"{path}: filename should start with {lc_id:04d}_")
        url = re.search(r"https://leetcode\.com/problems/[\w-]+/", doc)
        pattern = re.search(r"^Pattern:\s+(.+)$", doc, re.M)
        solved = re.search(r"^Solved:\s+(\S+)$", doc, re.M)
        if not url or not pattern or not solved:
            sys.exit(f"{path}: header needs a LeetCode URL, 'Pattern:' and 'Solved:' lines")
        found[lc_id] = {
            "id": lc_id, "title": title, "difficulty": difficulty,
            "module": FOLDER_MODULE[folder], "pattern": pattern.group(1).strip(),
            "solved": solved.group(1), "url": url.group(0),
            "path": path.relative_to(ROOT).as_posix(),
        }
    return found


def read_stubs():
    """problems/**/*.py -> {id: (path, [function names])} from 'LC NNN.' docstrings."""
    stubs = {}
    for path in sorted((ROOT / "problems").glob("m*/*.py")):
        text = path.read_text(encoding="utf-8")
        for name, lc_id in re.findall(r'def (\w+)\(.*?\).*?:\n\s+"""LC (\d+)\.', text):
            entry = stubs.setdefault(int(lc_id), (path.relative_to(ROOT).as_posix(), []))
            entry[1].append(name)
    return stubs


# ------------------------------------------------------------------ build text

def stats(writeups, stubs):
    b75 = {p[1]: p for p in BLIND_75}
    solved = {i for i in b75 if i in writeups or i in SOLVED_WITHOUT_WRITEUP}
    for i in writeups:                      # consistency check: catalog vs folder
        if i in b75 and writeups[i]["module"] != b75[i][0]:
            sys.exit(f"{writeups[i]['path']}: Blind 75 puts #{i} in module {b75[i][0]}")
    def by_level(ids):
        return {lvl: sum(1 for i in ids if b75[i][4] == lvl) for lvl in LEVELS}
    return {
        "b75": b75,
        "solved": solved,
        "totals": by_level(b75),
        "solved_by": by_level(solved),
        "written_b75": {i for i in writeups if i in b75},
        "extras": [w for i, w in writeups.items() if i not in b75],
        "stubbed": {i for i in stubs if i in b75},
    }


def build_problems_md(writeups, stubs, st):
    n_solved, total = len(st["solved"]), len(st["b75"])
    lines = [
        "# Problems", "", GENERATED, "",
        "The **Blind 75**, the best-known curated list of interview problems, grouped",
        "by this repo's modules. Every ID, title, link, and difficulty is checked",
        "against LeetCode (`python3 tools/verify_catalog.py`).", "",
        f"**Solved {n_solved} / {total}** `{bar(n_solved, total)}` "
        f"{round(100 * n_solved / total)}%  ·  "
        + "  ·  ".join(f"{DOT[l]} {st['solved_by'][l]}/{st['totals'][l]}" for l in LEVELS),
        "",
        "| Mark | Meaning |", "|:-:|---|",
        "| ✅ | solved |",
        "| 📝 | written up with review notes and tests, in [`leetcode/`](leetcode/) |",
        "| 🧪 | practice stub with tests, in [`problems/`](problems/) |",
        "| 🔒 | LeetCode Premium (NeetCode has free versions) |",
        "",
        "After the Blind 75, the natural next list is the **NeetCode 150**: the same",
        "18 topics, with 75 more problems that smooth out the jumps in difficulty.",
    ]
    for num, name, _ in MODULES:
        rows = [p for p in BLIND_75 if p[0] == num]
        if not rows:
            continue
        done = sum(1 for p in rows if p[1] in st["solved"])
        lines += ["", f"## {num} · {name}  <sub>{done} / {len(rows)}</sub>", "",
                  "| | # | Problem | Difficulty | In this repo |",
                  "|:-:|--:|---|---|---|"]
        for _, lc_id, title, slug, difficulty, premium in rows:
            mark = "✅" if lc_id in st["solved"] else ""
            lock = " 🔒" if premium else ""
            extras = []
            if lc_id in writeups:
                extras.append(f"📝 [my solution]({writeups[lc_id]['path']})")
            if lc_id in stubs:
                path, names = stubs[lc_id]
                extras.append("🧪 " + ", ".join(f"[`{n}`]({path})" for n in names))
            lines.append(f"| {mark} | {lc_id} | [{title}]({lc_url(slug)}){lock} | "
                         f"{DOT[difficulty]} {difficulty} | {' · '.join(extras)} |")
    if st["extras"]:
        lines += ["", "## Extra practice (not in the Blind 75)", "",
                  "| | # | Problem | Difficulty | In this repo |", "|:-:|--:|---|---|---|"]
        for w in sorted(st["extras"], key=lambda w: (w["module"], w["id"])):
            lines.append(f"| ✅ | {w['id']} | [{w['title']}]({w['url']}) | {DOT[w['difficulty']]} "
                         f"{w['difficulty']} | 📝 [my solution]({w['path']}) |")
    lines += ["", "[← back to the repo](README.md)", ""]
    return "\n".join(lines)


def build_leetcode_table(writeups, st):
    rows = sorted(writeups.values(), key=lambda w: (w["module"], w["id"]))
    lines = [GENERATED, "",
             "| # | Problem | Difficulty | Module | Pattern | List | Solved |",
             "|--:|---|---|---|---|---|---|"]
    for w in rows:
        rel = w["path"][len("leetcode/"):]
        lst = "Blind 75" if w["id"] in st["b75"] else "extra"
        lines.append(f"| {w['id']} | [{w['title']}]({rel}) | {DOT[w['difficulty']]} "
                     f"{w['difficulty']} | {w['module']} {MODULE_NAME[w['module']]} | "
                     f"{w['pattern']} | {lst} | {w['solved']} |")
    return "\n".join(lines)


def build_readme_progress(writeups, st):
    n_solved, total = len(st["solved"]), len(st["b75"])
    t, s = st["totals"], st["solved_by"]
    def row(label, counts, total_n):
        return f"| {label} | " + " | ".join(str(counts[l]) for l in LEVELS) + f" | **{total_n}** |"
    written = {l: sum(1 for i in st["written_b75"] if st["b75"][i][4] == l) for l in LEVELS}
    stubbed = {l: sum(1 for i in st["stubbed"] if st["b75"][i][4] == l) for l in LEVELS}
    lines = [GENERATED, "",
             f"**Blind 75: {n_solved} / {total} solved** `{bar(n_solved, total)}` "
             f"{round(100 * n_solved / total)}%", "",
             "| | 🟢 Easy | 🟡 Medium | 🔴 Hard | Total |", "|---|--:|--:|--:|--:|",
             row("Blind 75", t, total),
             row("Solved", s, n_solved),
             row("Written up with review notes", written, len(st["written_b75"])),
             row("Practice stubs with tests", stubbed, len(st["stubbed"]))]
    if st["extras"]:
        lines += ["", f"Plus {len(st['extras'])} extra problem"
                      f"{'s' if len(st['extras']) != 1 else ''} outside the Blind 75, "
                      "in [`leetcode/`](leetcode/)."]
    return "\n".join(lines)


def build_roadmap_table(writeups, st):
    """Per module: Blind 75 progress, and which study materials exist."""
    lines = [GENERATED, "",
             "| # | Module | The pattern, in one line | Blind 75 solved | In this repo |",
             "|---|---|---|--:|---|"]
    for num, name, folder in MODULES:
        have = []
        note = sorted(ROOT.glob(f"notes/{num}_*.md"))
        if note:
            have.append(f"[notes]({note[0].relative_to(ROOT).as_posix()})")
        sheet = sorted(ROOT.glob(f"cheatsheets/{num}_*.md"))
        if sheet:
            have.append(f"[cheatsheet]({sheet[0].relative_to(ROOT).as_posix()})")
        stub_dir = sorted(p for p in ROOT.glob(f"problems/m{num}_*") if p.is_dir())
        if stub_dir:
            have.append(f"[practice]({stub_dir[0].relative_to(ROOT).as_posix()}/)")
        n_written = sum(1 for w in writeups.values() if w["module"] == num)
        if n_written:
            have.append(f"[{n_written} write-up{'s' if n_written != 1 else ''}]"
                        f"(leetcode/{folder}/)")
        rows = [p for p in BLIND_75 if p[0] == num]
        done = sum(1 for p in rows if p[1] in st["solved"])
        solved = f"{done} / {len(rows)}" if rows else "—"
        lines.append(f"| {num} | {name} | {MODULE_SUMMARY[num]} | {solved} | "
                     f"{' · '.join(have)} |")
    return "\n".join(lines)


def replace_between(text, start, end, body, path):
    pattern = re.compile(re.escape(start) + r".*?" + re.escape(end), re.S)
    if not pattern.search(text):
        sys.exit(f"{path}: missing markers {start} ... {end}")
    return pattern.sub(lambda _: f"{start}\n{body}\n{end}", text)


# ------------------------------------------------------------------------ main

def main():
    check = "--check" in sys.argv
    writeups, stubs = read_writeups(), read_stubs()
    st = stats(writeups, stubs)

    outputs = {ROOT / "PROBLEMS.md": build_problems_md(writeups, stubs, st)}
    lc_readme = ROOT / "leetcode" / "README.md"
    outputs[lc_readme] = replace_between(
        lc_readme.read_text(encoding="utf-8"), "<!-- index:start -->", "<!-- index:end -->",
        build_leetcode_table(writeups, st), lc_readme)
    readme = ROOT / "README.md"
    outputs[readme] = replace_between(
        readme.read_text(encoding="utf-8"), "<!-- progress:start -->", "<!-- progress:end -->",
        build_readme_progress(writeups, st), readme)

    roadmap = ROOT / "ROADMAP.md"
    outputs[roadmap] = replace_between(
        roadmap.read_text(encoding="utf-8"), "<!-- modules:start -->", "<!-- modules:end -->",
        build_roadmap_table(writeups, st), roadmap)

    stale = [p for p, text in outputs.items()
             if not p.exists() or p.read_text(encoding="utf-8") != text]
    if check:
        if stale:
            print("out of date (run ./sync):")
            for p in stale:
                print("  " + p.relative_to(ROOT).as_posix())
            sys.exit(1)
        print("indexes are up to date")
        return
    for p in stale:
        p.write_text(outputs[p], encoding="utf-8")
    print(f"Blind 75: {len(st['solved'])}/{len(st['b75'])} solved · "
          f"{len(writeups)} written up · {len(st['stubbed'])} stubbed · "
          f"updated {len(stale)} file(s)")


if __name__ == "__main__":
    main()
